services:
  s2s-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../server:/app/server
      - ../frontend:/app/frontend
      - ../docker/hf_cache:/root/.cache/huggingface
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
